server:
  port: 8081 # 포트 중복 방지
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true
        same-site: none

spring:
  application:
    name: closet
  mvc:
    dispatch-options-request: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/closet}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:closet-user}
    password: ${DATABASE_PASSWORD:closet_1234}

  cache:
    # type: caffeine
    type: redis
    cache-names:
      - users # 추가 해주시면 됩니다. (yml 리스트 형식으로)
    redis:
      enable-statistics: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: validate   # (dev환경이면 update OK / prod는 validate 권장)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest #latest

      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


dm:
  api:
    base-url: ${DM_API_BASE_URL:http://localhost:8080}

security:
  jwt:
    issuer: closet
    secret: ${JWT_SECRET:376352270f35f8070b7a7e2ae299ca43}
    access-token-validity-seconds: 3600 # 1시간
    refresh-token-validity-seconds: 1204000 # 14일

management:
  server:
    port: 9102
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
